defaults:
  app:
    publishMetaData: !env:bool PUBLISH_METADATA
    workerTableName: WMWorkers
    workerTypeTableName: WMWorkerTypes
    workerTypeErrorTableName: WMWorkerTypeErrors
    workersExpirationTime: '-7 days' # Anything older than a week goes away
    errorsExpirationTime: '-4 days' # Anything older than a few days goes away
    provisionerId: worker-manager
  monitoring:
    enable: !env:bool MONITORING_ENABLE
    pretty: !env:bool PRETTY_LOGGING
    level: !env LEVEL
  taskcluster:
    rootUrl: !env TASKCLUSTER_ROOT_URL
    credentials:
      clientId: !env TASKCLUSTER_CLIENT_ID
      accessToken: !env TASKCLUSTER_ACCESS_TOKEN
  azure:
    accountId: !env AZURE_ACCOUNT
  server:
    port: !env:number PORT
    env: !env NODE_ENV
    forceSSL: !env:bool FORCE_SSL
    trustProxy: !env:bool TRUST_PROXY
  providers: !env:json PROVIDERS

test:
  monitoring:
    level: debug
    pretty: false
    enable: true
    mock: true
  server:
    port: 60409
    env: 'development'
    forceSSL: false
    trustProxy: false
  providers:
    testing1:
      implementation: testing
    testing2:
      implementation: testing
    static:
      implementation: static
